name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Set up OpenXM
      run: |
        sudo apt-get install -y build-essential m4 bison
        sudo apt-get install -y libx11-dev libxt-dev libxaw7-dev
        curl  -O "http://www.math.sci.kobe-u.ac.jp/pub/OpenXM/Head/openxm-head.tar.gz"
        tar xf openxm-head.tar.gz
        ls

    - name: Test
      run: go test -v ./...

    - name: Lint
      run: go vet -v ./...
